name: 'Prepare filtered release artifacts'

env:
  PREFIX: 'artifacts-sandbox'

on:
  release:
    types: [published]

jobs:
  prepare-filtered-release-artifacts:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the repository (shallow clone)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: ${{github.repository}}

      - name: Rename .github directory
        working-directory: ${{github.repository}}
        run: mv .github .github-sandbox
  
      - name: Archive the repository
        working-directory: ${{github.repository}}
        run: git archive -o ../${{env.PREFIX}}-${{github.event.release.tag_name}}.zip HEAD

      - name: Check out the repository wiki (shallow clone)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ${{github.repository}}.wiki
          path: ${{github.repository}}.wiki

      - name: Archive the repository wiki
        working-directory: ${{github.repository}}.wiki
        run: git archive -o ../${{env.PREFIX}}-${{github.event.release.tag_name}}-wiki.zip HEAD
  
      - name: Upload artifacts to existing release
        run: |
          find
          gh release upload ${{github.event.release.tag_name}} ${{env.PREFIX}}-${{github.event.release.tag_name}}.zip ${{env.PREFIX}}-${{github.event.release.tag_name}}-wiki.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
